---
galaxy_info:
  author: Richard Slater
  description: "Role to install Neovim from source on Debian/Ubuntu"
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - nvim
    - neovim
    - editor
dependencies: []
