---
oh_my_posh_bin_path: "/usr/local/bin/oh-my-posh"

# Architecture mapping for Oh My Posh downloads
oh_my_posh_arch_map:
  x86_64: "amd64"
  aarch64: "arm64"

oh_my_posh_version: "v31.3.0"

oh_my_posh_checksums:
  amd64: "sha256:92a253b607dbc632f9e45c9de06cb9650a1a3e7c36df2012a7b7600f22dcad80"
  arm64: "sha256:6388a11cf0e228e591a36d6a6024ec73dbf649d5b53f3442d85bb37f1871f1ed"

oh_my_posh_arch: "{{ oh_my_posh_arch_map[ansible_architecture] | default('unsupported') }}"
oh_my_posh_checksum: "{{ oh_my_posh_checksums[oh_my_posh_arch] | default(omit) }}"
oh_my_posh_supported_architectures:
  - x86_64
  - aarch64
