---
packages:
  - dnsutils
  - btop
  - yamllint
  - jq
  - yq
  - shellcheck
  - libclang-dev

unlisted_packages:
  - name: Dive
    source: https://github.com/wagoodman/dive/releases/download/v0.13.1/dive_0.13.1_linux_amd64.deb

# geerlingguy.go role variables - Go 1.26.5
go_version: "1.26.5"
go_install_clean: true
go_checksum: "5c2c3b16caefa1d968a94c1daca04a7ca301a496d9b086e17ad77bb81393f053"

uv_tools:
  - pre-commit
