---
galaxy_info:
  author: Richard Slater
  description: "Ansible role to install 'bat', a modern alternative to 'cat'."
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Archlinux
      versions:
        - all
  galaxy_tags:
    - bat
    - cat
    - cli
dependencies: []
