---
galaxy_info:
  author: Richard Slater
  description: "Ansible role to install tmux from source."
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - tmux
    - terminal
dependencies: []
