---
galaxy_info:
  author: Richard Slater
  description: Ansible role to install Rootless Networking
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: CentOS
      versions:
        - all
dependencies: []
