---
galaxy_info:
  author: "Richard Slater"
  description: "Ansible role to install and configure Oh My Posh"
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
dependencies: []
